from __future__ import annotations
from typing import Protocol, runtime_checkable, Any
import numpy as np

Array = np.ndarray | float

@runtime_checkable
class Truth(Protocol):
    def sample(self, n: int, seed: int | None = None) -> np.ndarray: ...
    def cdf_truth(self, t: Array) -> Array: ...
    def pdf_truth(self, x: Array) -> Array: ...

@runtime_checkable
class PredictiveState(Protocol):
    ...

@runtime_checkable
class PredictiveMethod(Protocol):
    def init_state(self, **kwargs: Any) -> PredictiveState: ...
    def update(self, state: PredictiveState, x: float) -> PredictiveState: ...
    def cdf_est(self, state: PredictiveState, t: Array) -> Array: ...
    def pdf_est(self, state: PredictiveState, x: Array) -> Array: ...
